fix: correctly place new notes in most cases
exception: when scrolling up the notes are still placed too high up, but the remaining ones don't move, which is good